{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6bea1842-4c4a-48c6-9dab-2ec18360b60e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Database Fundamentals</th>\n",
       "      <th>Computer Architecture</th>\n",
       "      <th>Distributed Computing Systems</th>\n",
       "      <th>Cyber Security</th>\n",
       "      <th>Networking</th>\n",
       "      <th>Software Development</th>\n",
       "      <th>Programming Skills</th>\n",
       "      <th>Project Management</th>\n",
       "      <th>Computer Forensics Fundamentals</th>\n",
       "      <th>Technical Communication</th>\n",
       "      <th>AI ML</th>\n",
       "      <th>Software Engineering</th>\n",
       "      <th>Business Analysis</th>\n",
       "      <th>Communication skills</th>\n",
       "      <th>Data Science</th>\n",
       "      <th>Troubleshooting skills</th>\n",
       "      <th>Graphics Designing</th>\n",
       "      <th>Role</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Professional</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Oracle Database Administration (DBA)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Professional</td>\n",
       "      <td>Poor</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Oracle Database Administration (DBA)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Professional</td>\n",
       "      <td>Beginner</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Oracle Database Administration (DBA)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Professional</td>\n",
       "      <td>Average</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Oracle Database Administration (DBA)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Professional</td>\n",
       "      <td>Intermediate</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Not Interested</td>\n",
       "      <td>Oracle Database Administration (DBA)</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  Database Fundamentals Computer Architecture Distributed Computing Systems  \\\n",
       "0          Professional        Not Interested                Not Interested   \n",
       "1          Professional                  Poor                Not Interested   \n",
       "2          Professional              Beginner                Not Interested   \n",
       "3          Professional               Average                Not Interested   \n",
       "4          Professional          Intermediate                Not Interested   \n",
       "\n",
       "   Cyber Security      Networking Software Development Programming Skills  \\\n",
       "0  Not Interested  Not Interested       Not Interested     Not Interested   \n",
       "1  Not Interested  Not Interested       Not Interested     Not Interested   \n",
       "2  Not Interested  Not Interested       Not Interested     Not Interested   \n",
       "3  Not Interested  Not Interested       Not Interested     Not Interested   \n",
       "4  Not Interested  Not Interested       Not Interested     Not Interested   \n",
       "\n",
       "  Project Management Computer Forensics Fundamentals Technical Communication  \\\n",
       "0     Not Interested                  Not Interested          Not Interested   \n",
       "1     Not Interested                  Not Interested          Not Interested   \n",
       "2     Not Interested                  Not Interested          Not Interested   \n",
       "3     Not Interested                  Not Interested          Not Interested   \n",
       "4     Not Interested                  Not Interested          Not Interested   \n",
       "\n",
       "            AI ML Software Engineering Business Analysis Communication skills  \\\n",
       "0  Not Interested       Not Interested    Not Interested       Not Interested   \n",
       "1  Not Interested       Not Interested    Not Interested       Not Interested   \n",
       "2  Not Interested       Not Interested    Not Interested       Not Interested   \n",
       "3  Not Interested       Not Interested    Not Interested       Not Interested   \n",
       "4  Not Interested       Not Interested    Not Interested       Not Interested   \n",
       "\n",
       "     Data Science Troubleshooting skills Graphics Designing  \\\n",
       "0  Not Interested         Not Interested     Not Interested   \n",
       "1  Not Interested         Not Interested     Not Interested   \n",
       "2  Not Interested         Not Interested     Not Interested   \n",
       "3  Not Interested         Not Interested     Not Interested   \n",
       "4  Not Interested         Not Interested     Not Interested   \n",
       "\n",
       "                                   Role  \n",
       "0  Oracle Database Administration (DBA)  \n",
       "1  Oracle Database Administration (DBA)  \n",
       "2  Oracle Database Administration (DBA)  \n",
       "3  Oracle Database Administration (DBA)  \n",
       "4  Oracle Database Administration (DBA)  "
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "df1 = pd.read_csv(\"career (4).csv\", dtype=str)\n",
    "df = df1.copy()\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "aad61370-7caa-46b1-b67a-cac13aa9a823",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Database Fundamentals= ['Professional' 'Not Interested' 'Poor' 'Beginner' 'Average'\n",
      " 'Intermediate' 'Excellent']\n",
      "Computer Architecture= ['Not Interested' 'Poor' 'Beginner' 'Average' 'Intermediate' 'Excellent'\n",
      " 'Professional']\n",
      "Leadership_Experience= ['Not Interested' 'Poor' 'Beginner' 'Average' 'Intermediate' 'Excellent'\n",
      " 'Professional']\n",
      "Cyber Security\t= ['Not Interested' 'Poor' 'Beginner' 'Average' 'Intermediate' 'Excellent'\n",
      " 'Professional']\n",
      "Networking= ['Not Interested' 'Poor' 'Beginner' 'Average' 'Intermediate' 'Excellent'\n",
      " 'Professional']\n",
      "Software Development= ['Not Interested' 'Poor' 'Beginner' 'Average' 'Intermediate' 'Excellent'\n",
      " 'Professional']\n",
      "Programming Skills= ['Not Interested' 'Poor' 'Beginner' 'Average' 'Intermediate' 'Excellent'\n",
      " 'Professional']\n",
      "Project Management= ['Not Interested' 'Poor' 'Beginner' 'Average' 'Intermediate' 'Excellent'\n",
      " 'Professional']\n",
      "Computer Forensics Fundamentals= ['Not Interested' 'Poor' 'Beginner' 'Average' 'Intermediate' 'Excellent'\n",
      " 'Professional']\n",
      "Technical Communication= ['Not Interested' 'Poor' 'Beginner' 'Average' 'Intermediate' 'Excellent'\n",
      " 'Professional']\n",
      "AI ML= ['Not Interested' 'Poor' 'Beginner' 'Average' 'Intermediate' 'Excellent'\n",
      " 'Professional']\n",
      "Software Engineering= ['Not Interested' 'Poor' 'Beginner' 'Average' 'Intermediate' 'Excellent'\n",
      " 'Professional']\n",
      "Business Analysis= ['Not Interested' 'Poor' 'Beginner' 'Average' 'Intermediate' 'Excellent'\n",
      " 'Professional']\n",
      "Communication skills= ['Not Interested' 'Poor' 'Beginner' 'Average' 'Intermediate' 'Excellent'\n",
      " 'Professional']\n",
      "Data Science= ['Not Interested' 'Poor' 'Beginner' 'Average' 'Intermediate' 'Excellent'\n",
      " 'Professional']\n",
      "Troubleshooting skills= ['Not Interested' 'Poor' 'Beginner' 'Average' 'Intermediate' 'Excellent'\n",
      " 'Professional']\n",
      "Graphics Designing= ['Not Interested' 'Poor' 'Beginner' 'Average' 'Intermediate' 'Excellent'\n",
      " nan 'Professional']\n",
      "Role= ['Oracle Database Administration (DBA)' 'Embedded Systems Engineering'\n",
      " 'IT Support and Application Management'\n",
      " 'Cybersecurity and Ethical Hacking'\n",
      " 'Network Engineering and Infrastructure' 'Full-Stack Web Development'\n",
      " 'API Development and Integration' 'Project Management Professional (PMP)'\n",
      " 'Digital Forensics and Incident Response (DFIR)'\n",
      " 'Technical Writing and Documentation'\n",
      " 'Artificial Intelligence and Machine Learning'\n",
      " 'Software Testing and Quality Assurance (QA)'\n",
      " 'Business Analysis and Requirements Management'\n",
      " 'Customer Service and Relationship Management'\n",
      " 'Data Science and Advanced Analytics'\n",
      " 'IT Support and Helpdesk Management'\n",
      " 'Graphic Design and Visual Communication']\n"
     ]
    }
   ],
   "source": [
    "\n",
    "x=df['Database Fundamentals'].unique().astype(str)\n",
    "y=df['Computer Architecture'].unique()\n",
    "z=df['Distributed Computing Systems'].unique()\n",
    "f=df['Cyber Security'].unique()\n",
    "c=df['Networking'].unique()\n",
    "a=df['Software Development'].unique()\n",
    "b=df['Programming Skills'].unique()\n",
    "d=df['Project Management'].unique()\n",
    "e=df['Computer Forensics Fundamentals'].unique()\n",
    "g=df['Technical Communication'].unique()\n",
    "h=df['AI ML'].unique()\n",
    "i=df['Software Engineering'].unique()\n",
    "j=df['Business Analysis'].unique()\n",
    "k=df['Communication skills'].unique()\n",
    "l=df['Data Science'].unique()\n",
    "m=df['Troubleshooting skills'].unique()\n",
    "n=df['Graphics Designing'].unique()\n",
    "o=df['Role'].unique()\n",
    "\n",
    "print(\"Database Fundamentals=\",x)\n",
    "print(\"Computer Architecture=\",y)\n",
    "print(\"Leadership_Experience=\",z)\n",
    "print(\"Cyber Security\t=\",f)\n",
    "print(\"Networking=\",c)\n",
    "print(\"Software Development=\",a)\n",
    "print(\"Programming Skills=\",b)\n",
    "print(\"Project Management=\",d)\n",
    "print(\"Computer Forensics Fundamentals=\",e)\n",
    "print(\"Technical Communication=\",g)\n",
    "print(\"AI ML=\",h)\n",
    "print(\"Software Engineering=\",i)\n",
    "print(\"Business Analysis=\",j)\n",
    "print(\"Communication skills=\",k)\n",
    "print(\"Data Science=\",l)\n",
    "print(\"Troubleshooting skills=\",m)\n",
    "print(\"Graphics Designing=\",n)\n",
    "print(\"Role=\",o)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "67bf044e-6e91-4ce8-a0de-b98c280f5a4f",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.preprocessing import LabelEncoder\n",
    "\n",
    "label_encoder = LabelEncoder()\n",
    "df['Database Fundamentals'] = label_encoder.fit_transform(df['Database Fundamentals'])\n",
    "df['Computer Architecture'] = label_encoder.fit_transform(df['Computer Architecture'])\n",
    "df['Distributed Computing Systems'] = label_encoder.fit_transform(df['Distributed Computing Systems'])\n",
    "df['Cyber Security'] = label_encoder.fit_transform(df['Cyber Security'])\n",
    "df['Networking'] = label_encoder.fit_transform(df['Networking'])\n",
    "df['Software Development'] = label_encoder.fit_transform(df['Software Development'])\n",
    "df['Programming Skills'] = label_encoder.fit_transform(df['Programming Skills'])\n",
    "df['Project Management'] = label_encoder.fit_transform(df['Project Management'])\n",
    "df['Computer Forensics Fundamentals'] = label_encoder.fit_transform(df['Computer Forensics Fundamentals'])\n",
    "df['Technical Communication'] = label_encoder.fit_transform(df['Technical Communication'])\n",
    "df['AI ML'] = label_encoder.fit_transform(df['AI ML'])\n",
    "df['Software Engineering'] = label_encoder.fit_transform(df['Software Engineering'])\n",
    "df['Business Analysis'] = label_encoder.fit_transform(df['Business Analysis'])\n",
    "df['Communication skills'] = label_encoder.fit_transform(df['Communication skills'])\n",
    "df['Data Science'] = label_encoder.fit_transform(df['Data Science'])\n",
    "df['Troubleshooting skills'] = label_encoder.fit_transform(df['Troubleshooting skills'])\n",
    "df['Graphics Designing'] = label_encoder.fit_transform(df['Graphics Designing'])\n",
    "df['Role'] = label_encoder.fit_transform(df['Role'])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "7444a63c-a707-49cd-a08b-9b0b46dc94a8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Database Fundamentals</th>\n",
       "      <th>Computer Architecture</th>\n",
       "      <th>Distributed Computing Systems</th>\n",
       "      <th>Cyber Security</th>\n",
       "      <th>Networking</th>\n",
       "      <th>Software Development</th>\n",
       "      <th>Programming Skills</th>\n",
       "      <th>Project Management</th>\n",
       "      <th>Computer Forensics Fundamentals</th>\n",
       "      <th>Technical Communication</th>\n",
       "      <th>AI ML</th>\n",
       "      <th>Software Engineering</th>\n",
       "      <th>Business Analysis</th>\n",
       "      <th>Communication skills</th>\n",
       "      <th>Data Science</th>\n",
       "      <th>Troubleshooting skills</th>\n",
       "      <th>Graphics Designing</th>\n",
       "      <th>Role</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>6</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>6</td>\n",
       "      <td>5</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>6</td>\n",
       "      <td>1</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>6</td>\n",
       "      <td>0</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>6</td>\n",
       "      <td>3</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>6</td>\n",
       "      <td>2</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>6</td>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>6</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>6</td>\n",
       "      <td>1</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>6</td>\n",
       "      <td>0</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>6</td>\n",
       "      <td>3</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>6</td>\n",
       "      <td>2</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>6</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>6</td>\n",
       "      <td>5</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>6</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>6</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>6</td>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>6</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>6</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>6</td>\n",
       "      <td>5</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    Database Fundamentals  Computer Architecture  \\\n",
       "0                       6                      4   \n",
       "1                       6                      5   \n",
       "2                       6                      1   \n",
       "3                       6                      0   \n",
       "4                       6                      3   \n",
       "5                       6                      2   \n",
       "6                       6                      4   \n",
       "7                       6                      5   \n",
       "8                       6                      1   \n",
       "9                       6                      0   \n",
       "10                      6                      3   \n",
       "11                      6                      2   \n",
       "12                      6                      4   \n",
       "13                      6                      5   \n",
       "14                      6                      1   \n",
       "15                      6                      0   \n",
       "16                      6                      3   \n",
       "17                      6                      2   \n",
       "18                      6                      4   \n",
       "19                      6                      5   \n",
       "\n",
       "    Distributed Computing Systems  Cyber Security  Networking  \\\n",
       "0                               4               4           4   \n",
       "1                               4               4           4   \n",
       "2                               4               4           4   \n",
       "3                               4               4           4   \n",
       "4                               4               4           4   \n",
       "5                               4               4           4   \n",
       "6                               5               5           5   \n",
       "7                               5               5           5   \n",
       "8                               5               5           5   \n",
       "9                               5               5           5   \n",
       "10                              5               5           5   \n",
       "11                              5               5           5   \n",
       "12                              1               1           1   \n",
       "13                              1               1           1   \n",
       "14                              1               1           1   \n",
       "15                              1               1           1   \n",
       "16                              1               1           1   \n",
       "17                              1               1           1   \n",
       "18                              0               0           0   \n",
       "19                              0               0           0   \n",
       "\n",
       "    Software Development  Programming Skills  Project Management  \\\n",
       "0                      4                   4                   4   \n",
       "1                      4                   4                   4   \n",
       "2                      4                   4                   4   \n",
       "3                      4                   4                   4   \n",
       "4                      4                   4                   4   \n",
       "5                      4                   4                   4   \n",
       "6                      5                   5                   5   \n",
       "7                      5                   5                   5   \n",
       "8                      5                   5                   5   \n",
       "9                      5                   5                   5   \n",
       "10                     5                   5                   5   \n",
       "11                     5                   5                   5   \n",
       "12                     1                   1                   1   \n",
       "13                     1                   1                   1   \n",
       "14                     1                   1                   1   \n",
       "15                     1                   1                   1   \n",
       "16                     1                   1                   1   \n",
       "17                     1                   1                   1   \n",
       "18                     0                   0                   0   \n",
       "19                     0                   0                   0   \n",
       "\n",
       "    Computer Forensics Fundamentals  Technical Communication  AI ML  \\\n",
       "0                                 4                        4      4   \n",
       "1                                 4                        4      4   \n",
       "2                                 4                        4      4   \n",
       "3                                 4                        4      4   \n",
       "4                                 4                        4      4   \n",
       "5                                 4                        4      4   \n",
       "6                                 5                        5      5   \n",
       "7                                 5                        5      5   \n",
       "8                                 5                        5      5   \n",
       "9                                 5                        5      5   \n",
       "10                                5                        5      5   \n",
       "11                                5                        5      5   \n",
       "12                                1                        1      1   \n",
       "13                                1                        1      1   \n",
       "14                                1                        1      1   \n",
       "15                                1                        1      1   \n",
       "16                                1                        1      1   \n",
       "17                                1                        1      1   \n",
       "18                                0                        0      0   \n",
       "19                                0                        0      0   \n",
       "\n",
       "    Software Engineering  Business Analysis  Communication skills  \\\n",
       "0                      4                  4                     4   \n",
       "1                      4                  4                     4   \n",
       "2                      4                  4                     4   \n",
       "3                      4                  4                     4   \n",
       "4                      4                  4                     4   \n",
       "5                      4                  4                     4   \n",
       "6                      5                  5                     5   \n",
       "7                      5                  5                     5   \n",
       "8                      5                  5                     5   \n",
       "9                      5                  5                     5   \n",
       "10                     5                  5                     5   \n",
       "11                     5                  5                     5   \n",
       "12                     1                  1                     1   \n",
       "13                     1                  1                     1   \n",
       "14                     1                  1                     1   \n",
       "15                     1                  1                     1   \n",
       "16                     1                  1                     1   \n",
       "17                     1                  1                     1   \n",
       "18                     0                  0                     0   \n",
       "19                     0                  0                     0   \n",
       "\n",
       "    Data Science  Troubleshooting skills  Graphics Designing  Role  \n",
       "0              4                       4                   4    13  \n",
       "1              4                       4                   4    13  \n",
       "2              4                       4                   4    13  \n",
       "3              4                       4                   4    13  \n",
       "4              4                       4                   4    13  \n",
       "5              4                       4                   4    13  \n",
       "6              5                       5                   5    13  \n",
       "7              5                       5                   5    13  \n",
       "8              5                       5                   5    13  \n",
       "9              5                       5                   5    13  \n",
       "10             5                       5                   5    13  \n",
       "11             5                       5                   5    13  \n",
       "12             1                       1                   1    13  \n",
       "13             1                       1                   1    13  \n",
       "14             1                       1                   1    13  \n",
       "15             1                       1                   1    13  \n",
       "16             1                       1                   1    13  \n",
       "17             1                       1                   1    13  \n",
       "18             0                       0                   0    13  \n",
       "19             0                       0                   0    13  "
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head(20)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "fa071fc3-7872-48c0-9287-f6b523e2bccd",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([13,  7, 10,  4, 12,  8,  0, 14,  6, 16,  1, 15,  2,  3,  5, 11,  9])"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df['Role'].unique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "d6daddd4-7583-4b58-84cb-1720d7751ef3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "13    540\n",
       "16    540\n",
       "11    540\n",
       "5     540\n",
       "3     540\n",
       "2     540\n",
       "15    540\n",
       "1     540\n",
       "6     540\n",
       "7     540\n",
       "14    540\n",
       "0     540\n",
       "8     540\n",
       "12    540\n",
       "4     540\n",
       "10    540\n",
       "9     539\n",
       "Name: Role, dtype: int64"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df['Role'].value_counts()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "6cafacbe-737f-4cef-937d-af269505317b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Database Fundamentals</th>\n",
       "      <th>Computer Architecture</th>\n",
       "      <th>Distributed Computing Systems</th>\n",
       "      <th>Cyber Security</th>\n",
       "      <th>Networking</th>\n",
       "      <th>Software Development</th>\n",
       "      <th>Programming Skills</th>\n",
       "      <th>Project Management</th>\n",
       "      <th>Computer Forensics Fundamentals</th>\n",
       "      <th>Technical Communication</th>\n",
       "      <th>AI ML</th>\n",
       "      <th>Software Engineering</th>\n",
       "      <th>Business Analysis</th>\n",
       "      <th>Communication skills</th>\n",
       "      <th>Data Science</th>\n",
       "      <th>Troubleshooting skills</th>\n",
       "      <th>Graphics Designing</th>\n",
       "      <th>Role</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>count</th>\n",
       "      <td>9179.000000</td>\n",
       "      <td>9179.000000</td>\n",
       "      <td>9179.000000</td>\n",
       "      <td>9179.000000</td>\n",
       "      <td>9179.000000</td>\n",
       "      <td>9179.000000</td>\n",
       "      <td>9179.000000</td>\n",
       "      <td>9179.000000</td>\n",
       "      <td>9179.000000</td>\n",
       "      <td>9179.000000</td>\n",
       "      <td>9179.000000</td>\n",
       "      <td>9179.000000</td>\n",
       "      <td>9179.000000</td>\n",
       "      <td>9179.000000</td>\n",
       "      <td>9179.000000</td>\n",
       "      <td>9179.000000</td>\n",
       "      <td>9179.000000</td>\n",
       "      <td>9179.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean</th>\n",
       "      <td>2.705959</td>\n",
       "      <td>2.705959</td>\n",
       "      <td>2.705959</td>\n",
       "      <td>2.705959</td>\n",
       "      <td>2.705959</td>\n",
       "      <td>2.705959</td>\n",
       "      <td>2.705959</td>\n",
       "      <td>2.705959</td>\n",
       "      <td>2.705959</td>\n",
       "      <td>2.705959</td>\n",
       "      <td>2.705959</td>\n",
       "      <td>2.705959</td>\n",
       "      <td>2.705959</td>\n",
       "      <td>2.705959</td>\n",
       "      <td>2.705959</td>\n",
       "      <td>2.705959</td>\n",
       "      <td>2.706068</td>\n",
       "      <td>7.999891</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>std</th>\n",
       "      <td>1.850403</td>\n",
       "      <td>1.850403</td>\n",
       "      <td>1.850403</td>\n",
       "      <td>1.850403</td>\n",
       "      <td>1.850403</td>\n",
       "      <td>1.850403</td>\n",
       "      <td>1.850403</td>\n",
       "      <td>1.850403</td>\n",
       "      <td>1.850403</td>\n",
       "      <td>1.850403</td>\n",
       "      <td>1.850403</td>\n",
       "      <td>1.850403</td>\n",
       "      <td>1.850403</td>\n",
       "      <td>1.850403</td>\n",
       "      <td>1.850403</td>\n",
       "      <td>1.850403</td>\n",
       "      <td>1.850626</td>\n",
       "      <td>4.899502</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>min</th>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25%</th>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>4.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50%</th>\n",
       "      <td>3.000000</td>\n",
       "      <td>3.000000</td>\n",
       "      <td>3.000000</td>\n",
       "      <td>3.000000</td>\n",
       "      <td>3.000000</td>\n",
       "      <td>3.000000</td>\n",
       "      <td>3.000000</td>\n",
       "      <td>3.000000</td>\n",
       "      <td>3.000000</td>\n",
       "      <td>3.000000</td>\n",
       "      <td>3.000000</td>\n",
       "      <td>3.000000</td>\n",
       "      <td>3.000000</td>\n",
       "      <td>3.000000</td>\n",
       "      <td>3.000000</td>\n",
       "      <td>3.000000</td>\n",
       "      <td>3.000000</td>\n",
       "      <td>8.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>75%</th>\n",
       "      <td>4.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>12.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>max</th>\n",
       "      <td>6.000000</td>\n",
       "      <td>6.000000</td>\n",
       "      <td>6.000000</td>\n",
       "      <td>6.000000</td>\n",
       "      <td>6.000000</td>\n",
       "      <td>6.000000</td>\n",
       "      <td>6.000000</td>\n",
       "      <td>6.000000</td>\n",
       "      <td>6.000000</td>\n",
       "      <td>6.000000</td>\n",
       "      <td>6.000000</td>\n",
       "      <td>6.000000</td>\n",
       "      <td>6.000000</td>\n",
       "      <td>6.000000</td>\n",
       "      <td>6.000000</td>\n",
       "      <td>6.000000</td>\n",
       "      <td>7.000000</td>\n",
       "      <td>16.000000</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       Database Fundamentals  Computer Architecture  \\\n",
       "count            9179.000000            9179.000000   \n",
       "mean                2.705959               2.705959   \n",
       "std                 1.850403               1.850403   \n",
       "min                 0.000000               0.000000   \n",
       "25%                 1.000000               1.000000   \n",
       "50%                 3.000000               3.000000   \n",
       "75%                 4.000000               4.000000   \n",
       "max                 6.000000               6.000000   \n",
       "\n",
       "       Distributed Computing Systems  Cyber Security   Networking  \\\n",
       "count                    9179.000000     9179.000000  9179.000000   \n",
       "mean                        2.705959        2.705959     2.705959   \n",
       "std                         1.850403        1.850403     1.850403   \n",
       "min                         0.000000        0.000000     0.000000   \n",
       "25%                         1.000000        1.000000     1.000000   \n",
       "50%                         3.000000        3.000000     3.000000   \n",
       "75%                         4.000000        4.000000     4.000000   \n",
       "max                         6.000000        6.000000     6.000000   \n",
       "\n",
       "       Software Development  Programming Skills  Project Management  \\\n",
       "count           9179.000000         9179.000000         9179.000000   \n",
       "mean               2.705959            2.705959            2.705959   \n",
       "std                1.850403            1.850403            1.850403   \n",
       "min                0.000000            0.000000            0.000000   \n",
       "25%                1.000000            1.000000            1.000000   \n",
       "50%                3.000000            3.000000            3.000000   \n",
       "75%                4.000000            4.000000            4.000000   \n",
       "max                6.000000            6.000000            6.000000   \n",
       "\n",
       "       Computer Forensics Fundamentals  Technical Communication        AI ML  \\\n",
       "count                      9179.000000              9179.000000  9179.000000   \n",
       "mean                          2.705959                 2.705959     2.705959   \n",
       "std                           1.850403                 1.850403     1.850403   \n",
       "min                           0.000000                 0.000000     0.000000   \n",
       "25%                           1.000000                 1.000000     1.000000   \n",
       "50%                           3.000000                 3.000000     3.000000   \n",
       "75%                           4.000000                 4.000000     4.000000   \n",
       "max                           6.000000                 6.000000     6.000000   \n",
       "\n",
       "       Software Engineering  Business Analysis  Communication skills  \\\n",
       "count           9179.000000        9179.000000           9179.000000   \n",
       "mean               2.705959           2.705959              2.705959   \n",
       "std                1.850403           1.850403              1.850403   \n",
       "min                0.000000           0.000000              0.000000   \n",
       "25%                1.000000           1.000000              1.000000   \n",
       "50%                3.000000           3.000000              3.000000   \n",
       "75%                4.000000           4.000000              4.000000   \n",
       "max                6.000000           6.000000              6.000000   \n",
       "\n",
       "       Data Science  Troubleshooting skills  Graphics Designing         Role  \n",
       "count   9179.000000             9179.000000         9179.000000  9179.000000  \n",
       "mean       2.705959                2.705959            2.706068     7.999891  \n",
       "std        1.850403                1.850403            1.850626     4.899502  \n",
       "min        0.000000                0.000000            0.000000     0.000000  \n",
       "25%        1.000000                1.000000            1.000000     4.000000  \n",
       "50%        3.000000                3.000000            3.000000     8.000000  \n",
       "75%        4.000000                4.000000            4.000000    12.000000  \n",
       "max        6.000000                6.000000            7.000000    16.000000  "
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.describe()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "f95b0e47-33c8-4ca7-923a-a3d4a4f57b67",
   "metadata": {},
   "outputs": [],
   "source": [
    "from imblearn.over_sampling import SMOTE\n",
    "\n",
    "smote = SMOTE(random_state=42)\n",
    "\n",
    "X = df.drop('Role', axis=1)\n",
    "y = df['Role']\n",
    "\n",
    "X_resampled, y_resampled = smote.fit_resample(X, y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "3596aab1-8814-4383-a7ed-bde62a16dd2f",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.3, random_state=150)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "3efc4b30-c27a-43a6-a920-8b8080ea6957",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(6426, 17)"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_train.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "de01439e-71fc-4a69-8063-10100f2c4ade",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "scaler = StandardScaler()\n",
    "X_train_scaled = scaler.fit_transform(X_train)\n",
    "X_test_scaled = scaler.transform(X_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "ccf0a7ad-1051-4514-bd63-db2eb4c501e8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(6426, 17)"
      ]
     },
     "execution_count": 23,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_train_scaled.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "5ed6680f-5c3e-40e4-82fc-855a062a5c89",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: Logistic Regression\n",
      "Accuracy: 0.9520697167755992\n",
      "F1-Score: 0.9520703073183787\n",
      "==================================================\n",
      "Model: Support Vector Classifier\n",
      "Accuracy: 0.9084967320261438\n",
      "F1-Score: 0.8900909147100069\n",
      "==================================================\n",
      "Model: Random Forest Classifier\n",
      "Accuracy: 0.9310094408133623\n",
      "F1-Score: 0.9310020746713001\n",
      "==================================================\n",
      "Model: K Nearest Neighbors\n",
      "Accuracy: 0.8326071169208424\n",
      "F1-Score: 0.8406363611184856\n",
      "==================================================\n",
      "Model: Decision Tree Classifier\n",
      "Accuracy: 0.8006535947712419\n",
      "F1-Score: 0.804246944934832\n",
      "==================================================\n",
      "Model: Gaussian Naive Bayes\n",
      "Accuracy: 0.8198983297022513\n",
      "F1-Score: 0.8388715275390254\n",
      "==================================================\n",
      "Model: AdaBoost Classifier\n",
      "Accuracy: 0.7868554829339143\n",
      "F1-Score: 0.7895981186800893\n",
      "==================================================\n",
      "Model: Gradient Boosting Classifier\n",
      "Accuracy: 0.9320987654320988\n",
      "F1-Score: 0.9322663469255489\n",
      "==================================================\n",
      "Model: XGBoost Classifier\n",
      "Accuracy: 0.9625998547567175\n",
      "F1-Score: 0.9626941760604079\n",
      "==================================================\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.tree import DecisionTreeClassifier\n",
    "from sklearn.naive_bayes import GaussianNB\n",
    "from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier\n",
    "from xgboost import XGBClassifier\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.feature_selection import SelectKBest, f_classif\n",
    "from sklearn.metrics import accuracy_score, f1_score\n",
    "import warnings\n",
    "\n",
    "warnings.filterwarnings(\"ignore\", category=UserWarning)\n",
    "warnings.filterwarnings(\"ignore\", category=FutureWarning)\n",
    "pca = PCA(n_components=16)  \n",
    "X_train_pca = pca.fit_transform(X_train)\n",
    "X_test_pca = pca.transform(X_test)\n",
    "\n",
    "selector = SelectKBest(f_classif, k=16) \n",
    "X_train_selected = selector.fit_transform(X_train_pca, y_train)\n",
    "X_test_selected = selector.transform(X_test_pca)\n",
    "\n",
    "models = {\n",
    "    \"Logistic Regression\": LogisticRegression(C=0.1, random_state=150),\n",
    "    \"Support Vector Classifier\": SVC(C=0.1, probability=True, random_state=150),\n",
    "    \"Random Forest Classifier\": RandomForestClassifier(\n",
    "        max_depth=10, min_samples_split=10, n_estimators=50, random_state=150\n",
    "    ),\n",
    "    \"K Nearest Neighbors\": KNeighborsClassifier(n_neighbors=5),\n",
    "    \"Decision Tree Classifier\": DecisionTreeClassifier(\n",
    "        max_depth=10, min_samples_split=10, random_state=150\n",
    "    ),\n",
    "    \"Gaussian Naive Bayes\": GaussianNB(),\n",
    "    \"AdaBoost Classifier\": AdaBoostClassifier(n_estimators=50, random_state=150),\n",
    "    \"Gradient Boosting Classifier\": GradientBoostingClassifier(\n",
    "        max_depth=5, n_estimators=50, random_state=150\n",
    "    ),\n",
    "    \"XGBoost Classifier\": XGBClassifier(\n",
    "        max_depth=5, n_estimators=50, use_label_encoder=False, eval_metric='mlogloss', random_state=150\n",
    "    ),\n",
    "}\n",
    "results = {}\n",
    "for name, model in models.items():\n",
    "    model.fit(X_train_selected, y_train)\n",
    "    y_pred = model.predict(X_test_selected)\n",
    "    accuracy = accuracy_score(y_test, y_pred)\n",
    "    f1 = f1_score(y_test, y_pred, average='weighted')\n",
    "    \n",
    "    results[name] = {\n",
    "        \"Accuracy\": accuracy,\n",
    "        \"F1-Score\": f1,\n",
    "    }\n",
    "\n",
    "for name, metrics in results.items():\n",
    "    print(f\"Model: {name}\")\n",
    "    print(f\"Accuracy: {metrics['Accuracy']}\")\n",
    "    print(f\"F1-Score: {metrics['F1-Score']}\")\n",
    "    print(\"=\" * 50)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "07e2c971-c936-492f-98d2-3f0dc91b3c24",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Accuracy:  0.9629629629629629\n"
     ]
    }
   ],
   "source": [
    "model = XGBClassifier()\n",
    "\n",
    "model.fit(X_train_selected, y_train)\n",
    "\n",
    "y_pred = model.predict(X_test_selected)\n",
    "print(\"Accuracy: \",accuracy_score(y_test, y_pred))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "fdfdf256-fb0b-49e6-bf57-dbb641733b8b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Actual Label : 15\n",
      "Model Prediction : 15\n",
      "Wow! Model doing well.....\n"
     ]
    }
   ],
   "source": [
    "# test 1\n",
    "print(\"Actual Label :\", y_test.iloc[13])\n",
    "print(\"Model Prediction :\",model.predict(X_test_selected[13].reshape(1,-1))[0])\n",
    "if y_test.iloc[13]==model.predict(X_test_selected[13].reshape(1,-1)):\n",
    "    print(\"Wow! Model doing well.....\")\n",
    "else:\n",
    "    print(\"not sure......\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "ee99e3ea-04f0-4333-ae81-32da9c7a4c8a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Actual Label : 4\n",
      "Model Prediction : 4\n",
      "Wow! Model doing well.....\n"
     ]
    }
   ],
   "source": [
    "# test 2\n",
    "print(\"Actual Label :\", y_test.iloc[50])\n",
    "print(\"Model Prediction :\",model.predict(X_test_selected[50].reshape(1,-1))[0])\n",
    "if y_test.iloc[50]==model.predict(X_test_selected[50].reshape(1,-1)):\n",
    "    print(\"Wow! Model doing well.....\")\n",
    "else:\n",
    "    print(\"not sure......\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "a44a6f51-15b2-40ba-88cb-ebbf92ae150f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting fastapi\n",
      "  Downloading fastapi-0.115.12-py3-none-any.whl (95 kB)\n",
      "                                              0.0/95.2 kB ? eta -:--:--\n",
      "     ------------                             30.7/95.2 kB 1.3 MB/s eta 0:00:01\n",
      "     -------------------------------------- 95.2/95.2 kB 903.4 kB/s eta 0:00:00\n",
      "Requirement already satisfied: uvicorn in c:\\users\\mega2\\anaconda3\\lib\\site-packages (0.34.0)\n",
      "Requirement already satisfied: scikit-learn in c:\\users\\mega2\\anaconda3\\lib\\site-packages (1.2.2)\n",
      "Collecting starlette<0.47.0,>=0.40.0 (from fastapi)\n",
      "  Downloading starlette-0.46.1-py3-none-any.whl (71 kB)\n",
      "                                              0.0/72.0 kB ? eta -:--:--\n",
      "     ---------------------------------------  71.7/72.0 kB 1.3 MB/s eta 0:00:01\n",
      "     ---------------------------------------- 72.0/72.0 kB 1.3 MB/s eta 0:00:00\n",
      "Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 in c:\\users\\mega2\\anaconda3\\lib\\site-packages (from fastapi) (2.8.2)\n",
      "Requirement already satisfied: typing-extensions>=4.8.0 in c:\\users\\mega2\\anaconda3\\lib\\site-packages (from fastapi) (4.13.2)\n",
      "Requirement already satisfied: click>=7.0 in c:\\users\\mega2\\anaconda3\\lib\\site-packages (from uvicorn) (8.0.4)\n",
      "Requirement already satisfied: h11>=0.8 in c:\\users\\mega2\\anaconda3\\lib\\site-packages (from uvicorn) (0.14.0)\n",
      "Requirement already satisfied: numpy>=1.17.3 in c:\\users\\mega2\\anaconda3\\lib\\site-packages (from scikit-learn) (1.24.3)\n",
      "Requirement already satisfied: scipy>=1.3.2 in c:\\users\\mega2\\anaconda3\\lib\\site-packages (from scikit-learn) (1.10.1)\n",
      "Requirement already satisfied: joblib>=1.1.1 in c:\\users\\mega2\\anaconda3\\lib\\site-packages (from scikit-learn) (1.2.0)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in c:\\users\\mega2\\anaconda3\\lib\\site-packages (from scikit-learn) (2.2.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\mega2\\anaconda3\\lib\\site-packages (from click>=7.0->uvicorn) (0.4.6)\n",
      "Requirement already satisfied: annotated-types>=0.4.0 in c:\\users\\mega2\\anaconda3\\lib\\site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.20.1 in c:\\users\\mega2\\anaconda3\\lib\\site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (2.20.1)\n",
      "Collecting anyio<5,>=3.6.2 (from starlette<0.47.0,>=0.40.0->fastapi)\n",
      "  Downloading anyio-4.9.0-py3-none-any.whl (100 kB)\n",
      "                                              0.0/100.9 kB ? eta -:--:--\n",
      "     -----------------------                 61.4/100.9 kB 3.2 MB/s eta 0:00:01\n",
      "     -------------------------------------- 100.9/100.9 kB 1.9 MB/s eta 0:00:00\n",
      "Requirement already satisfied: idna>=2.8 in c:\\users\\mega2\\anaconda3\\lib\\site-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi) (3.4)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\users\\mega2\\anaconda3\\lib\\site-packages (from anyio<5,>=3.6.2->starlette<0.47.0,>=0.40.0->fastapi) (1.2.0)\n",
      "Installing collected packages: anyio, starlette, fastapi\n",
      "  Attempting uninstall: anyio\n",
      "    Found existing installation: anyio 3.5.0\n",
      "    Uninstalling anyio-3.5.0:\n",
      "      Successfully uninstalled anyio-3.5.0\n",
      "Successfully installed anyio-4.9.0 fastapi-0.115.12 starlette-0.46.1\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install fastapi uvicorn scikit-learn\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "19162813-2f75-4804-a433-b9687ada1842",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['Models/model.pkl']"
      ]
     },
     "execution_count": 30,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import os\n",
    "import joblib\n",
    "if not os.path.exists('Models'):\n",
    "    os.makedirs('Models')\n",
    "joblib.dump(scaler, \"Models/scaler.pkl\")\n",
    "joblib.dump(pca, \"Models/pca.pkl\")\n",
    "joblib.dump(selector, \"Models/selector.pkl\")\n",
    "joblib.dump(model, \"Models/model.pkl\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6690e56a-b6b0-40d0-947e-f57ae6f89201",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:     Started server process [4064]\n",
      "INFO:     Waiting for application startup.\n",
      "INFO:     Application startup complete.\n",
      "INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:     127.0.0.1:64703 - \"GET /docs HTTP/1.1\" 200 OK\n",
      "INFO:     127.0.0.1:64703 - \"GET /openapi.json HTTP/1.1\" 200 OK\n",
      "INFO:     127.0.0.1:64776 - \"POST /recommend HTTP/1.1\" 200 OK\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mega2\\anaconda3\\Lib\\site-packages\\sklearn\\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names\n",
      "  warnings.warn(\n",
      "C:\\Users\\mega2\\anaconda3\\Lib\\site-packages\\sklearn\\base.py:439: UserWarning: X does not have valid feature names, but PCA was fitted with feature names\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:     127.0.0.1:64833 - \"POST /recommend HTTP/1.1\" 200 OK\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\mega2\\anaconda3\\Lib\\site-packages\\sklearn\\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names\n",
      "  warnings.warn(\n",
      "C:\\Users\\mega2\\anaconda3\\Lib\\site-packages\\sklearn\\base.py:439: UserWarning: X does not have valid feature names, but PCA was fitted with feature names\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "from fastapi import FastAPI, HTTPException\n",
    "from pydantic import BaseModel\n",
    "from fastapi.responses import JSONResponse\n",
    "import joblib\n",
    "import uvicorn\n",
    "import nest_asyncio\n",
    "\n",
    "# تحميل النماذج\n",
    "scaler = joblib.load(\"Models/scaler.pkl\")\n",
    "pca = joblib.load(\"Models/pca.pkl\")\n",
    "selector = joblib.load(\"Models/selector.pkl\")\n",
    "model = joblib.load(\"Models/model.pkl\")\n",
    "\n",
    "# قائمة أسماء الوظائف\n",
    "class_names = [\n",
    "    'Oracle Database Administration (DBA)',\n",
    "    'Embedded Systems Engineering',\n",
    "    'IT Support and Application Management',\n",
    "    'Cybersecurity and Ethical Hacking',\n",
    "    'Network Engineering and Infrastructure',\n",
    "    'Full-Stack Web Development',\n",
    "    'API Development and Integration',\n",
    "    'Project Management Professional (PMP)',\n",
    "    'Digital Forensics and Incident Response (DFIR)',\n",
    "    'Technical Writing and Documentation',\n",
    "    'Artificial Intelligence and Machine Learning',\n",
    "    'Software Testing and Quality Assurance (QA)',\n",
    "    'Business Analysis and Requirements Management',\n",
    "    'Customer Service and Relationship Management',\n",
    "    'Data Science and Advanced Analytics',\n",
    "    'IT Support and Helpdesk Management',\n",
    "    'Graphic Design and Visual Communication'\n",
    "]\n",
    "\n",
    "# إنشاء تطبيق FastAPI\n",
    "app = FastAPI()\n",
    "\n",
    "# نموذج إدخال المستخدم\n",
    "class UserInput(BaseModel):\n",
    "    Database_Fundamentals: str\n",
    "    Computer_Architecture: str\n",
    "    Leadership_Experience: str\n",
    "    Cyber_Security: str\n",
    "    Networking: str\n",
    "    Software_Development: str\n",
    "    Programming_Skills: str\n",
    "    Project_Management: str\n",
    "    Computer_Forensics_Fundamentals: str\n",
    "    Technical_Communication: str\n",
    "    AI_ML: str\n",
    "    Software_Engineering: str\n",
    "    Business_Analysis: str\n",
    "    Communication_Skills: str\n",
    "    Data_Science: str\n",
    "    Troubleshooting_Skills: str\n",
    "    Graphics_Designing: str\n",
    "\n",
    "# دالة لتحويل الخبرة إلى قيم رقمية\n",
    "def map_experience(value):\n",
    "    mapping = {\"Excellent\": 3, \"Average\": 2, \"Beginner\": 1, \"Not Interested\": 0}\n",
    "    return mapping.get(value, 0)\n",
    "\n",
    "# نقطة نهاية للصفحة الرئيسية\n",
    "@app.get(\"/\")\n",
    "def read_root():\n",
    "    return JSONResponse(content={\"message\": \"Welcome to the recommendation API! Please use POST /recommend.\"})\n",
    "\n",
    "# نقطة نهاية لتقديم التوصيات\n",
    "@app.post(\"/recommend\")\n",
    "def recommendations(user_input: UserInput):\n",
    "    try:\n",
    "        # تحويل المدخلات إلى مصفوفة\n",
    "        feature_array = np.array([[\n",
    "            map_experience(user_input.Database_Fundamentals),\n",
    "            map_experience(user_input.Computer_Architecture),\n",
    "            map_experience(user_input.Leadership_Experience),\n",
    "            map_experience(user_input.Cyber_Security),\n",
    "            map_experience(user_input.Networking),\n",
    "            map_experience(user_input.Software_Development),\n",
    "            map_experience(user_input.Programming_Skills),\n",
    "            map_experience(user_input.Project_Management),\n",
    "            map_experience(user_input.Computer_Forensics_Fundamentals),\n",
    "            map_experience(user_input.Technical_Communication),\n",
    "            map_experience(user_input.AI_ML),\n",
    "            map_experience(user_input.Software_Engineering),\n",
    "            map_experience(user_input.Business_Analysis),\n",
    "            map_experience(user_input.Communication_Skills),\n",
    "            map_experience(user_input.Data_Science),\n",
    "            map_experience(user_input.Troubleshooting_Skills),\n",
    "            map_experience(user_input.Graphics_Designing)\n",
    "        ]])\n",
    "\n",
    "        # التحقق من عدد المدخلات\n",
    "        if feature_array.shape[1] != 17:\n",
    "            raise HTTPException(status_code=400, detail=\"The number of inputs does not match the model's expectations.\")\n",
    "\n",
    "        # تطبيق التحجيم (Scaling)\n",
    "        scaled_features = scaler.transform(feature_array)\n",
    "\n",
    "        # تطبيق PCA\n",
    "        pca_features = pca.transform(scaled_features)\n",
    "\n",
    "        # تطبيق Selector\n",
    "        selected_features = selector.transform(pca_features)\n",
    "\n",
    "        # الحصول على احتمالات الفئات\n",
    "        probabilities = model.predict_proba(selected_features)\n",
    "\n",
    "        # الحصول على أفضل 3 فئات\n",
    "        top_classes_idx = np.argsort(-probabilities[0])[:3]\n",
    "\n",
    "        # تصفية الفهارس غير الصالحة\n",
    "        top_classes_idx = [idx for idx in top_classes_idx if 0 <= idx < len(class_names)]\n",
    "\n",
    "        # إنشاء التوصيات\n",
    "        if not top_classes_idx:\n",
    "            raise HTTPException(status_code=404, detail=\"No valid recommendations found.\")\n",
    "\n",
    "        recommendations = [{\"job\": class_names[idx]} for idx in top_classes_idx]\n",
    "\n",
    "        return {\"recommendations\": recommendations}\n",
    "\n",
    "    except Exception as e:\n",
    "        raise HTTPException(status_code=500, detail=f\"An error occurred: {str(e)}\")\n",
    "\n",
    "# تشغيل التطبيق\n",
    "if __name__ == \"__main__\":\n",
    "    nest_asyncio.apply()\n",
    "    uvicorn.run(app, host=\"127.0.0.1\", port=8080)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "e9645a6f-815c-43a3-8c79-fde10b16c487",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: nest_asyncio in c:\\users\\mega2\\anaconda3\\lib\\site-packages (1.5.6)\n"
     ]
    }
   ],
   "source": [
    "!pip install nest_asyncio"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c0356cb1-e4a3-44ab-9ff9-90be5a7cfaca",
   "metadata": {},
   "outputs": [],
   "source": [
    "curl -X 'POST' \\\n",
    "  'http://127.0.0.1:8000/recommend' \\\n",
    "  -H 'Content-Type: application/json' \\\n",
    "  -d '{\n",
    "    \"Database_Fundamentals\": \"Excellent\",\n",
    "    \"Computer_Architecture\": \"Average\",\n",
    "    \"Leadership_Experience\": \"Excellent\",\n",
    "    \"Cyber_Security\": \"Beginner\",\n",
    "    \"Networking\": \"Average\",\n",
    "    \"Software_Development\": \"Excellent\",\n",
    "    \"Programming_Skills\": \"Excellent\",\n",
    "    \"Project_Management\": \"Beginner\",\n",
    "    \"Computer_Forensics_Fundamentals\": \"Not Interested\",\n",
    "    \"Technical_Communication\": \"Excellent\",\n",
    "    \"AI_ML\": \"Average\",\n",
    "    \"Software_Engineering\": \"Beginner\",\n",
    "    \"Business_Analysis\": \"Not Interested\",\n",
    "    \"Communication_Skills\": \"Excellent\",\n",
    "    \"Data_Science\": \"Average\",\n",
    "    \"Troubleshooting_Skills\": \"Excellent\",\n",
    "    \"Graphics_Designing\": \"Not Interested\",\n",
    "    \"top_n\": 3\n",
    "  }'\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
